name: Windows Build
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: 'true'
      - name: Build wxwidgets
        run: |
             cd ..
             git clone https://github.com/wxWidgets/wxWidgets.git --recurse-submodules
             cd wxWidgets
             cmake -S . -B build
             cmake --build build --config Debug
      - name: Build
        run: |
             cd ${{ github.workspace }}\demo
             cmake ${{ github.workspace }}\demo\CMakeLists.txt -DwxWidgets_ROOT_DIR=..\..\wxWidgets
             cmake --build . --config Debug
             dir
